// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Editorsk
{
    internal sealed partial class Vsix
    {
        public const string Id = "13a2ec1a-6b20-46a9-af99-b1064b00c9a8";
        public const string Name = "Editor Enhancements";
        public const string Description = @"Provides additional features such as HTML and URL encodings, transformations and sorting of selected text the editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "editor, strings, lines, encoding";
    }
}
