// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Editorsk
{
    static class Vsix
    {
        public const string Id = "a3112f81-e423-4f88-9f2c-e089a309e48e";
        public const string Name = "Text Enhancements";
        public const string Description = "Provides additional features such as HTML and URL encodings, transformations and sorting of selected text the editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "editor, strings, lines, encoding";
    }
}
