// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Editorsk
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "3dc4f9d3-0070-4393-8c0b-c3952e944624";
        public const string guidTopMenuString = "f321cac5-e101-459b-b24e-ba72ad25a2f3";
        public const string guidEncodingCmdSetString = "02af2694-ed70-4c77-b1ab-e1ecb5eda6e7";
        public const string guidTransformCmdSetString = "f4c95200-781f-4ca3-b2c6-e6f444368df8";
        public const string guidLinesCmdSetString = "243f9ffe-bb22-44f7-bc28-75a5f69c6431";
        public const string HtmlCmdSetString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public const string CssCmdSetString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public const string JsonCmdSetString = "f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd";
        public const string guidXmlUiCmdsString = "fb87333b-16c8-400e-bc8f-f6b890410582";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidTopMenu = new Guid(guidTopMenuString);
        public static Guid guidEncodingCmdSet = new Guid(guidEncodingCmdSetString);
        public static Guid guidTransformCmdSet = new Guid(guidTransformCmdSetString);
        public static Guid guidLinesCmdSet = new Guid(guidLinesCmdSetString);
        public static Guid HtmlCmdSet = new Guid(HtmlCmdSetString);
        public static Guid CssCmdSet = new Guid(CssCmdSetString);
        public static Guid JsonCmdSet = new Guid(JsonCmdSetString);
        public static Guid guidXmlUiCmds = new Guid(guidXmlUiCmdsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopMenu = 0x3001;
        public const int EncodeMenu = 0x0100;
        public const int HtmlEncodingMenuGroup = 0x0110;
        public const int JavaScriptEncodingMenuGroup = 0x0120;
        public const int UrlEncodingMenuGroup = 0x0130;
        public const int cmdHtmlEncode = 0x0102;
        public const int cmdHtmlDecode = 0x0103;
        public const int cmdUrlEncode = 0x0106;
        public const int cmdUrlDecode = 0x0107;
        public const int cmdJavaScriptEncode = 0x0108;
        public const int cmdAttrEncode = 0x0109;
        public const int TransformMenu = 0x0100;
        public const int CasingTransformMenuGroup = 0x0110;
        public const int MiscTransformMenuGroup = 0x0120;
        public const int CryptoTransformMenuGroup = 0x0130;
        public const int cmdTitleCase = 0x0001;
        public const int cmdReverse = 0x0002;
        public const int cmdNormalize = 0x0003;
        public const int cmdMd5 = 0x0004;
        public const int cmdSha1 = 0x0005;
        public const int cmdSha256 = 0x0006;
        public const int cmdSha384 = 0x0007;
        public const int cmdSha512 = 0x0008;
        public const int LinesMenu = 0x0001;
        public const int LinesMenuGroup = 0x0002;
        public const int cmdSortAsc = 0x0003;
        public const int cmdSortDesc = 0x0004;
        public const int cmdRemoveDuplicateLines = 0x0005;
        public const int cmdRemoveEmptyLines = 0x0007;
        public const int htmlContextMenu = 0x0001;
        public const int CssContextMenu = 0x0002;
        public const int JsonContextMenu = 0x0003;
    }
}
